[package]
name = "text_deitor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12.1", features = ["tokio"] }
rfd = "0.15.3"
tokio = { version = "1.45.1", features = ["fs", "rt"] }

